#!/bin/bash

code=$1

if [ $code -eq 0 ];
then
	echo "Compiling code..."
	javac -d bin -sourcepath src src/com/adi/lifeonterminal/adiserver/AdiServerInit.java -proc:none
	if [ $? -eq 0 ];
	then
		echo "Code compiled!"
		java -Xms2g -Xmx2g -cp $CLASSPATH:bin com.adi.lifeonterminal.adiserver.AdiServerInit AdiServerConf
		cls
	fi
else
i
	java -Xms2g -Xmx2g -cp $CLASSPATH:bin com.adi.lifeonterminal.adiserver.AdiServerInit AdiServerConf
	cls
fi			 
